spring:
  application:
    name: docker-compose-gateway

server:
  port: 2333

eureka:
  client:
    service-url:
      defaultZone: http://docker-compose-eureka:1234/eureka/

zuul:
  routes:
    serviceId:
      serviceId: your_server_id
      path: /**
    serviceId2:
      serviceId: your_server2_id
      path: /**

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
